<?php

$DEFAULT_LANG = "en-en";
$LOADED_LANGUAGE = $DEFAULT_LANG;

if (isset($_GET['lang'])) {
    if (file_exists(__DIR__ . "/lang/" . $_GET['lang'] . ".txt")) {
        $LOADED_LANGUAGE = $_GET['lang'];
    }
}

function load_lang($ldl) {
    $language_contents = array();
    $handle = fopen(__DIR__ . "/lang/" . $ldl . ".txt", "r");
    if ($handle) {
        while (($line = fgets($handle)) !== false) {
            $language_contents[] = rtrim($line, "\r\n");
        }
        fclose($handle);
    }
    return $language_contents;
}

$LANGUAGE_CONTENTS = load_lang($LOADED_LANGUAGE);

$AVAILABLE_LANGUAGES = scandir(__DIR__ . "/lang/");
for ($i = 0; $i < count($AVAILABLE_LANGUAGES); $i++) {
    $AVAILABLE_LANGUAGES[$i] = substr($AVAILABLE_LANGUAGES[$i], 0, -4);
}

$AVAILABLE_LANGUAGES = array_unique($AVAILABLE_LANGUAGES);
array_shift($AVAILABLE_LANGUAGES);

$CONNECTION_TITLE = 0;
$INSCRIPTION_TITLE = 1;
$EMAIL_LABEL = 2;
$SECRET_LABEL = 3;
$CONFIRM_LABEL = 4;
$LANGUAGES_TITLE = 5;
$LANGUAGES_HEADER = 6;
$ROLE_SELECT_TITLE = 7;
$ROLE_SELECT_SUBTITLE = 8;

$FORUMS_TITLE = 9;
$FORUMS_OFFSET_LABEL = 10;
$FORUMS_RESOLVED_LABEL = 11;
$FORUMS_NAME_LABEL = 12;
$FORUMS_PREVIEW_LABEL = 13;
$FORUMS_DATE_LABEL = 14;
$FORUMS_RESOLVED_YES = 15;
$FORUMS_RESOLVED_NO = 16;

$ANNONCES_TITLE = 17;
$ANNONCES_OFFSET_LABEL = 18;
$ANNONCES_CATEGORY_LABEL = 19;
$ANNONCES_NAME_LABEL = 20;
$ANNONCES_PRICE_LABEL = 21;
$ANNONCES_DESCRIPTION_LABEL = 22;
$ANNONCES_DATE_LABEL = 23;
$ANNONCES_IMAGE_LABEL = 24;
$ANNONCES_STATE_LABEL = 25;

$FORUMS_REPLY_LABEL = 28;
$FORUMS_LIKE_LABEL = 29;
$FORUMS_DISLIKE_LABEL = 30;

$ANNONCE_SELLER_LABEL = 31;
$ANNONCE_BUYER_LABEL = 32;
$ANNONCE_MESSAGES_LABEL = 33;
$ANNONCE_BACK_LABEL = 34;
$ANNONCE_MESSAGE_LABEL = 35;
$ANNONCE_AUTHOR_LABEL = 36;
$ANNONCE_DATE_LABEL = 37;

$PREVIOUS_LABEL = 26;
$NEXT_LABEL = 27;

$MYAPPS_TITLE = 38;
$MYAPPS_WELCOME = 39;
$MYAPPS_ANNONCES = 40;
$MYAPPS_FORUMS = 41;
$MYAPPS_EVENEMENTS = 42;
$MYAPPS_TUTORIELS = 43;
$MYAPPS_LOGOUT = 44;

$INSCRIPTION_NOM_LABEL = 45;
$INSCRIPTION_PRENOM_LABEL = 46;
$INSCRIPTION_TELEPHONE_LABEL = 47;
$INSCRIPTION_ADRESSE_LABEL = 48;
$INSCRIPTION_CODE_POSTAL_LABEL = 49;
$INSCRIPTION_VILLE_LABEL = 50;
$INSCRIPTION_SIRET_LABEL = 51;

$CONNECTION_ERROR_LABEL = 52;
$INSCRIPTION_ERROR_LABEL = 53;

$ANNONCE_CREATE_TITLE = 54;
$ANNONCE_CREATE_SUBMIT_LABEL = 55;
$ANNONCE_DELETE_LABEL = 56;
$ANNONCE_NEW_LABEL = 57;

$FORUM_CREATE_TITLE = 58;
$FORUM_CREATE_CATEGORY_LABEL = 59;
$FORUM_CREATE_SUBMIT_LABEL = 60;
$FORUM_REPLY_SUBMIT_LABEL = 61;
$FORUM_RESOLVE_LABEL = 62;
$FORUM_NEW_LABEL = 63;

$EVENEMENTS_TITLE = 64;
$EVENEMENTS_STATUT_LABEL = 65;
$TUTORIELS_TITLE = 66;

$PLANNING_TITLE = 67;
$PLANNING_UPCOMING_TITLE = 68;
$PLANNING_OPEN_LABEL = 69;
$PLANNING_NEW_LABEL = 70;
$PLANNING_TITRE_LABEL = 71;
$PLANNING_DESCRIPTION_LABEL = 72;
$PLANNING_DATE_DEBUT_LABEL = 73;
$PLANNING_DATE_FIN_LABEL = 74;
$PLANNING_SUBMIT_LABEL = 75;
$PLANNING_EDIT_LABEL = 76;
$PLANNING_DELETE_LABEL = 77;

$PLANNING_JOIN_LABEL = 78;
$PLANNING_LEAVE_LABEL = 79;
$ANNONCE_MATERIAUX_LABEL = 80;
$ANNONCE_BUY_LABEL = 81;
$ANNONCE_BUY_ERROR_LABEL = 82;

$SCORE_LABEL = 83;
$INSCRIPTION_TYPE_LABEL = 84;
$INSCRIPTION_TYPE_PARTICULIER = 85;
$INSCRIPTION_TYPE_PRO = 86;
$INSCRIPTION_FORFAIT_LABEL = 87;
$INSCRIPTION_FORFAIT_GRATUIT = 88;
$INSCRIPTION_FORFAIT_PAYANT = 89;
$INSCRIPTION_ENTREPRISE_NOM_LABEL = 90;
$INSCRIPTION_ENTREPRISE_ADRESSE_LABEL = 91;
$INSCRIPTION_ENTREPRISE_CP_LABEL = 92;
$INSCRIPTION_ENTREPRISE_VILLE_LABEL = 93;
$INSCRIPTION_ENTREPRISE_SIRET_LABEL = 94;
$ANNONCE_EDIT_LABEL = 95;
$ANNONCE_EDIT_TITLE = 96;
$ANNONCE_ETAT_D = 97;
$ANNONCE_ETAT_V = 98;

$MYAPPS_CONTRATS = 99;
$MYAPPS_PROJETS = 100;
$MYAPPS_RELAIS = 101;
$MYAPPS_APPLICATIONS = 102;
$MYAPPS_ADMIN_APPLICATIONS = 103;
$CONTRATS_TITLE = 104;
$CONTRATS_SEARCH_ID_LABEL = 105;
$CONTRATS_SEARCH_Q_LABEL = 106;
$CONTRATS_SEARCH_SUBMIT = 107;
$CONTRATS_DEPENSE_LABEL = 108;
$CONTRATS_GAIN_LABEL = 109;
$CONTRATS_PDF_LABEL = 110;
$CONTRATS_DATE_DEBUT_LABEL = 111;
$CONTRATS_DATE_FIN_LABEL = 112;
$CONTRATS_NEW_LABEL = 113;
$CONTRATS_SUBMIT_LABEL = 114;
$PROJETS_TITLE = 115;
$PROJETS_NEW_LABEL = 116;
$PROJETS_TEXTE_LABEL = 117;
$PROJETS_SUBMIT_LABEL = 118;
$PROJETS_CAMPAGNE_LABEL = 119;
$PROJETS_CAMPAGNE_MONTANT_LABEL = 120;
$PROJETS_CAMPAGNE_SUCCESS = 121;
$RELAIS_TITLE = 122;
$RELAIS_BARCODE_LABEL = 123;
$APPLICATIONS_TITLE = 124;
$APPLICATIONS_OWNED_LABEL = 125;
$APPLICATIONS_BUY_LABEL = 126;
$APPLICATIONS_PAYMENT_SUCCESS = 127;
$APPLICATIONS_PAYMENT_ERROR = 128;
$ADMIN_APPLICATIONS_TITLE = 129;
$ADMIN_APPLICATIONS_SAVE_LABEL = 130;

$CONTRATS_SEARCH_TIERS_LABEL = 131;
$CONTRATS_TIERS_LABEL = 132;

$ADMIN_TITLE = 133;
$MYAPPS_ADMIN = 134;
$ADMIN_MODERATION_THREADS = 135;
$ADMIN_MODERATION_ANNONCES = 136;
$ADMIN_EVENEMENTS = 137;
$ADMIN_TUTORIELS = 138;
$ADMIN_CLIENTS = 139;
$ADMIN_DELETE_LABEL = 140;
$ADMIN_CLIENTS_ROLES_LABEL = 141;
$ADMIN_CLIENTS_GRANT_LABEL = 142;
$ADMIN_CLIENTS_REVOKE_LABEL = 143;
$ADMIN_CLIENTS_SEARCH_LABEL = 144;
$ADMIN_EVENEMENT_NEW_LABEL = 145;
$ADMIN_EVENEMENT_STATUT_P = 146;
$ADMIN_EVENEMENT_STATUT_C = 147;
$ADMIN_EVENEMENT_STATUT_A = 148;
$ADMIN_TUTORIEL_NEW_LABEL = 149;
$ADMIN_TUTORIEL_ARTICLE_LABEL = 150;
$ADMIN_TUTORIEL_VIDEO_LABEL = 151;
$ADMIN_SUBMIT_LABEL = 152;
$ADMIN_NO_ACCESS_LABEL = 153;